# Base configuration
@baseUrl=http://localhost:3000/v1/api/user
@apiKey = 71d9f89886c72c39ca939a3b6b0abcf101bad656a43b150658eb66111717b7ca
### Sign up
POST {{baseUrl}}/sign_up
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "username": "John Doe16",
    "email": "user16@ex.co",
    "password": "12345678"
}